sudo: false
language: node_js
cache:
  yarn: true
notifications:
  email: false
node_js:
  - '12'
install:
  - yarn
script:
  - yarn run lint
  - yarn run flow
  - yarn run cover
after_success:
  - bash <(curl -s https://codecov.io/bash)
  - semantic-release
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
